### ISSUE TITLE
Çeviri de bulunan üst tire javascript hatasına sebep oluyor.

### ISSUE THREAD

**Issue by hibrhmk** [epiksel/opencart-tr#6]
Çeviri dosyası marketplace/marketplace.php  46. satır

`$_['text_secure']        = 'PIN\'inizi geliştiriciler dahil herhangi birisine vermeyin. Bir uzantı satıcısının sizin için bir uzantı kurmasını istiyorsanız, onlara gerekli uzantıyı e-postayla göndermelisin.';`

![image](https://user-images.githubusercontent.com/52932792/158036348-54f8b3ad-da77-41a8-947b-647064c3672c.png)

![image](https://user-images.githubusercontent.com/52932792/158036364-cfd23434-cfb7-427b-80d3-91623eb1d5bc.png)

Bu hata yüzünden marketten bir şey kurulamıyor.

**Comment by eka7a** [comment]
Buradaki düzeltmeyi uygulayın. https://github.com/epiksel/opencart-tr/commit/8203fe0b6f3e6a8e985956476e4cef034c8f2023
